ISEIproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    #teacher urls

    path('teacherdashboard/', views.teacherdashboard, name='teacher_dashboard'),
    path('account_settings/', views.accountsettings, name='account_settings'),
    path('myPDAdashboard/<str:pk>', views.myPDAdashboard, name='myPDAdashboard'),

    path('update_pdainstance/<str:pk>/', views.updatePDAinstance, name="update_pdainstance"),
    path('delete_pdainstance/<str:pk>/', views.deletePDAinstance, name="delete_pdainstance"),


    #create PDA instances and records. View submitted PDAs
    #new record: pk - user ID, sy- School-year,  #existing record: recId - record ID
    path('create_pda/<str:recId>/', views.createPDA, name='create_pda'),
    path('create_record/<str:pk>/<str:sy>/', views.createrecord, name='create_record'),


    #principal urls
    path('principaldashboard/', views.principaldashboard, name='principal_dashboard'),
    #signs the record with recID
    path('principaldashboard/<str:recID>', views.principaldashboard, name='principal_dashboard'),
    
    path('teachercertification/', views.teachercertification, name='teacher_certification'),
    #signs the record with recID
    path('teachercertification/<str:recID>', views.teachercertification, name='teacher_certification'),



    #admin urls
    path('admindashboard/', views.admindashboard, name='admin_dashboard'),



#Unused
   path('teachers/', views.teachers, name="teachers"),


# authentication urls
    path('', views.loginpage, name='login'),
    path('register/', views.registerpage, name='register'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutuser, name='logout'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
         name="password_reset_complete"),
]

accounts/models.py
from django.db import models
from django.db.models.functions import Round
from django.conf import settings
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.core.validators import MinLengthValidator
from django.core.files.storage import FileSystemStorage


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=50, help_text='Enter the name of the school', unique=True, blank=False,
                            null=False)
    abbreviation = models.CharField(max_length=4, default=" ", help_text=' Enter the abbreviation for this school')
    school_code = models.CharField(max_length=15, help_text='Code to allow a user to register as principal',
                                   default="pxyughkn8986")
    ordering = ['name']

    def __str__(self):
        return self.name



fs = FileSystemStorage(location='static/media/ProfilePictures')

class Teacher(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    school = models.ForeignKey(School, on_delete=models.PROTECT, null=True, help_text="*Required")
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    profile_picture = models.ImageField(default='ProfilePictures/blank-profile.jpg', null=True, blank=True,storage=fs)

    CERTIFICATION_TYPES = {
        ('v', 'Vocational'),
        ('d', 'Designated'),
        ('c', 'Conditional'),
        ('e', 'Semi Professional'),
        ('b', 'Basic'),
        ('s', 'Standard'),
        ('p', 'Professional'),
    }
    current_certification = models.CharField(max_length=1, choices=sorted(CERTIFICATION_TYPES), null=True, blank=True)

    def __str__(self):
        return self.user.last_name + ', ' + self.user.first_name


class PDAType(models.Model):
    type = models.CharField(max_length=100, help_text='Describe the possible activities', null=False)
    CATEGORIES = (
        ('i', 'Independent'),
        ('g', 'Group'),
        ('c', 'Collaboration'),
        ('p', 'Presentation & Writing'),
    )
    category = models.CharField(max_length=1, choices=CATEGORIES, help_text="Choose a category", null=False)
    ceu_value = models.CharField(max_length=60, null=True, blank=True)

    def __str__(self):
        return self.get_category_display() + ' - ' + self.type


class SchoolYear(models.Model):
    name = models.CharField(max_length=9, unique=True)
    active_year = models.BooleanField(default=False)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(SchoolYear, self).save(*args, **kwargs)
        if self.active_year:
            all = SchoolYear.objects.exclude(id=self.id).update(active_year=False)


class PDARecord(models.Model):
    # entered by teacher at object creation
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT, null=False, blank=False)
    school_year = models.ForeignKey(SchoolYear, null=True, blank=True, on_delete=models.PROTECT)
    date_submitted = models.DateField(null=True, blank=True)
    principal_signed = models.BooleanField(null=False, default=False, blank=True)
    class Meta:
        unique_together = ('teacher', 'school_year',)
        ordering = ['school_year']

    # entered by teacher at object finalization
    summary = models.CharField(validators=[MinLengthValidator(1)], max_length=3000, blank=True, null=True,
                               help_text='Summarize what you have learned from the combined activities and how you '
                                         'plan to apply this learning to your classroom')



class PDAInstance(models.Model):
    # record contains teacher, school-year and summary
    pda_record = models.ForeignKey(PDARecord, on_delete=models.PROTECT, null=False, blank=False)
    pda_type = models.ForeignKey(PDAType, on_delete=models.PROTECT, null=False, blank=False)
    date_completed = models.DateField(null=False)
    description = models.CharField(validators=[MinLengthValidator(1)], max_length=3000, blank=False, null=False)

    # OR between those three
    ceu = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    clock_hours = models.DecimalField(max_digits=3, decimal_places=1, null=True, blank=True)
    pages = models.DecimalField(max_digits=3, decimal_places=0, null=True, blank=True)

    file = models.FileField(upload_to='documents/Supporting_Files/', null=True, blank=True)
    date_submitted = models.DateField(null=True, blank=True)

    submitted = models.BooleanField(null=False, default=False, blank=True)
    principal_signed = models.BooleanField(null=False, default=False, blank=True)
    isei_reviewed = models.BooleanField(null=False, default=False, blank=True)
    approved = models.BooleanField(null=False, default=False, blank=True)

    approved_ceu = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    approval_comment = models.CharField(max_length=300, null=True, blank=True)

    class Meta:
        ordering = ['pda_record']

    @property
    def status(self):
        return int(self.submitted == True) + int(self.principal_signed == True) *2 + int(self.isei_reviewed == True)*4 +int(self.approved == True) *8
    # 0 - New instance
    # 1 - Submitted instance
    # 2 - Denied by the principal (submitted=0, principal_signed = 1)
    # 3 - Signed by the principal
    # 4 - Summary denied, whole record returned (isei_reviewed = 1, submitted = 0, principal_signed = 0)
    # 5 - Resubmitted to principal (isei_reviewed = 1, submitted = 1, principal_signed = 0)
    # 6 - Record approved, individual instance denied ( isei_reviewed = 1, principal_signed = 1, submitted = 0)
    # 15 - Approved by ISEI

    def suggested_ceu(self):
        if self.approved:
            if self.ceu is not None:
                return self.ceu
            elif self.pages is not None:
                return round(self.pages / 100, 2)
            elif self.clock_hours is not None:
                return round(self.clock_hours / 10, 2)

    def __str__(self):
        return self.description

accounts/forms.py
from django.forms import ModelForm, modelformset_factory, ClearableFileInput
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms.models import inlineformset_factory
# from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
# from django.forms.models import BaseInlineFormSet
from .models import *


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        exclude = ['user']
        widgets = {
            'profile_picture': forms.FileInput(attrs={'size': 1}),
        }


class PDARecordForm(ModelForm):
    class Meta:
        model = PDARecord
        fields = ('school_year', 'date_submitted', 'summary')
        widgets = {
        #    'school_year': forms.TextInput(attrs={'class': 'form-controls', 'placehoder': 'Enter school year'}),
        #    'date_submitted': forms.DateField(attrs={'class': 'form-controls', 'placehoder': 'Enter date'}),
             'summary': forms.Textarea(
                attrs={'class': 'form-controls', 'placehoder': 'Enter summary for combined activities'})
        }


class PDAInstanceForm(ModelForm):
    class Meta:
        model = PDAInstance
        fields = ('pda_type','description', 'date_completed',  'pages', 'clock_hours', 'ceu', 'file')
        widgets = {
            'file': forms.FileInput(attrs={'size': 1}),
        }


PDAInstanceFormSet = inlineformset_factory(PDARecord, PDAInstance, form=PDAInstanceForm, extra=1,
                                           can_delete=False)

#class PDAInstanceFormSetHelper(FormHelper):
#    def __init__(self, *args, **kwargs):
#        super().__init__(*args, **kwargs)
#        self.form_method = 'post'
#        self.layout = Layout(
#            'pda_type',
#            'description','date_completed',
#            'pages', 'clock_hours', 'ceu', 'file'
#        )
#        self.render_required_fields = True



class DocumentForm(forms.Form): #unused but keeping it just in case
    name = forms.CharField(max_length=35, min_length=1)
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

accounts/templates/accounts/account_settings.html
{%  extends 'accounts/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'teacher_dashboard' %}"> &#8592; Back to HomePage</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
            {% if request.user.teacher.profile_picture %}

			    <img class="profile-pic" src="{% static '/media/ProfilePictures/' %}{{request.user.teacher.profile_picture}}" >
		    {% endif %}
		</div>
	</div>

    <div class="col-md-9">
		<div class="card card-body">

			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
                <div class="row">
                    <div class="col-2">
                        {{ user_form.first_name|as_crispy_field }}
                    </div>
                    <div class="col-2">
                        {{ user_form.last_name|as_crispy_field }}
                    </div>
                    <div class="col-3">
                        {{ user_form.email|as_crispy_field }}
                    </div>
                    <div class="col-3">
                        {{ teacher_form.phone_number|as_crispy_field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        {{ teacher_form.current_certification|as_crispy_field }}
                    </div>
                    <div class="col-3">
                        {{ teacher_form.school|as_crispy_field }}
                    </div>

                </div>
                <br>

                <div class="row">
                    <div class="col-3">
                        <p style="font-size: 14px">Change Profile Picture</p>
                        {{ teacher_form.profile_picture}}
                    </div>
                </div>
                <br>

			<input class="btn btn-default" type="submit" value="Update">
			</form>
		</div>
			{% for message in messages %}
	          <p id="messages">{{message}}</p>
	        {% endfor %}
	</div>
</div>


{% endblock %}

accounts/templates/accounts/admin_dashboard.html
{% extends 'accounts/main.html' %}

{% block content %}


<br>

<div class="row">
	<div class="col-md-5">
		<h5>Teachers:</h5>
		<hr>
		<div class="card card-body">
	
			<table class="table table-sm">
				<tr>
					<th>Teacher</th>
					<th>School</th>
				</tr>
				{% for teacher in teachers %}
					<tr>
						<td>{{teacher.user.username}} </td>
						<td>{{teacher.school}} </td>
					</tr>	

				{% endfor %}
					

			</table>
		</div>
	</div>

	<div class="col-md-7">
		<h5>Activities record</h5>
		<hr>
		<div class="card card-body">
			
			<table class="table table-sm">
				<tr>
					<th>Teacher</th>
					<th>Activity Type</th>
					<th>Date </th>
					<th>CEU</th>
					
				</tr>			
				{% for activity in activities %}
					<tr>
						<td>{{activity.pdarecord.teacher}} </td>
						<td>{{activity.type.get_category_display}} </td>
						<td>{{activity.date}} </td>
						<td>{{activity.CEUs}} </td>
						
					</tr>	

				{% endfor %}
			</table>
		</div>
	</div>

</div>

{% include 'accounts/status.html' %}

{% endblock %}

accounts/templates/accounts/create_pda.html
{% extends 'accounts/main.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}

{% if user_not_teacher %} <!--if it will be used by any other user-->
    {{ pda_record.teacher }}
{% endif %}
{{ pda_record.school_year }}

<!-- Table of activities-->
<div class="row">
    <div class="card card-body">
        <table class="table table-sm">
            <tr>
                <th>Activity Type</th><th>Date Completed</th><th>Description</th><th>ceu</th><th>clock_Hours</th><th>pages</th>
                <th>Supporting Docs</th>
                {% if pda_record.principal_signature == None %}
                    <th>Update</th><th>Remove</th>
                {% else %}
                    <th>Approved_CEU</th><th>Comment</th>
                {% endif %}
            </tr>
            {% for p in pda_instance %}
            <tr>
                <td>{{p.pda_type}}</td><td>{{p.date_completed}} </td><td>{{p.description}} </td>
                <td>{{p.ceu|default_if_none:""}}</td><td>{{p.clock_hours|default_if_none:""}}</td><td>{{p.pages|default_if_none:""}}</td>
                <td><a href="{%  static 'media/' %}{{ p.file }}">{{ p.file }}</a></td>
                {% if pda_record.principal_signature %}
                    <td>{{ p.approved_ceu }}</td>
                    <td>{{p.approval_comment}}</td>
                    {% else %}
                <td><a class = "btn btn-sm btn-info" href="{% url 'update_pdainstance' p.id %}">Update</a></td>
                <td><a class = "btn btn-sm btn-danger" href="{% url 'delete_pdainstance' p.id %}">Delete</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>


{% if pda_record.principal_signature  %}
<!-- If Activity is aleady submitted to ISEI, show summary and approved CEUs -->
    <div class="row">
        <div class="col"> Summary: {{pda_record.summary}}<br></div>
        <div class ="col-sm-2">
            {% if pda_record.total_approved_ceus  %}
             Approved CEUs: {{ pda_record.total_approved_ceus }}
            {% endif %}
        </div>
    </div>

{% else %}

<!-- If Activity is not yet submitted -->
    <form action=" " method="POST" id="add_activity" enctype="multipart/form-data">
        <!-- enter new activity-->    
        <div class="card card-body">
            <b> Enter new activity:</b><br>
            {% csrf_token %}        
            <div class="row">
            {{ instanceformset.management_form }}
            {% for f in instanceformset %}
                <div class="col-sm-3"> {{ f.pda_type|as_crispy_field}}</div>
                <div class="col-sm-2"> {{ f.description|as_crispy_field}}</div>
                <div class = "col-sm-2"> {{f.date_completed|as_crispy_field}} </div>               
                <div class = "col-sm"> {{f.ceu|as_crispy_field}} </div> 
                <div class = "col-sm-1">{{f.clock_hours|as_crispy_field}}</div>
                <div class = "col-sm"> {{f.pages|as_crispy_field}} </div>
                <div class = "col-sm" >
                    Supporting Documentation: <br>
                    {{f.file}} <br><br>
                     <input class = "btn btn-sm btn-default" type="submit" value="Add Activity" name = "add_activity"> </div>
                {% endfor %}
            </div>

                
            <div class="row">                
           
            <!-- update summary-->
                <div class = col-sm-9>
                <p id="school_year">{{record_form.school_year}}</p> <!-- hidden with the script below, needed for form submission-->
                {% csrf_token %}
                {{ record_form.summary|as_crispy_field }}
                
                <div class="col-sm-2">
                    <input class = "btn btn-sm btn-default" type="submit" value="Update Summary" name = "update_summary">
                </div>
                </div>            
            
            <div class="col-sm-3" style = "margin-top: 170px">
                <div class="card card-body" >
                    <!-- submit record-->
                    <p id="school_year2">{{record_form.school_year}}</p>
                    {% csrf_token %}
                    {{ record_form.date_submitted|as_crispy_field }}<i>*submit only when all activities for this school year have been entered</i> <br>
                    <input class = "btn btn-sm btn-danger" type="submit" value="Submit" name = "submit_record">
                </div>
            </div> 
           </div>
        </div>
    </form>

{% endif %}

    <script>
        document.getElementById("school_year").style.display = "none";
        document.getElementById("school_year2").style.display = "none";
    </script>

{% endblock %}

accounts/templates/accounts/delete_pdainstance.html
{% extends 'accounts/main.html' %} 
{% load static %}
{% block content %}	


<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<p> Are you sure you want to delete "{{item}}"? The operation can not be undone.</p>
			<form action="{% url 'delete_pdainstance' item.id %}" method="POST">
				{% csrf_token %}

					<a class="btn btn-warning" href="{%  url 'myPDAdashboard' item.pda_record.teacher.user.id %}">Cancel</a>

					<input class="btn btn-danger" type='submit' value ='Confirm'>
			</form>
		</div>
	</div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
    
<head>
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">


          <h3 id="form-title" >LOGIN</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form method="POST" action="">
            {% csrf_token %}
            <div class="input-group mb-3">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
              </div>

              <input type="text" name="username" placeholder="Username..." class="form-control">
            </div>

            <div class="input-group mb-2">
              <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
              </div>

                <input type="password" name="password" placeholder="Password..." class="form-control" >
            </div>

              <div class="d-flex justify-content-center mt-3 login_container">
                <input class="btn login_btn" type="submit" value="Login">
                </div>
          </form>

        </div>

        {% for message in messages %}
          <p id="messages">{{message}}</p>
        {% endfor %}      

        <div class="mt-4">
        
          <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
          </div>
          <div class="d-flex justify-content-center links">
            Forgot Password? <a href="{% url 'reset_password' %}" class="ml-2"> Reset Password</a>
          </div>
        
        </div>
      </div>
    </div>
  </div>
</body>

</html>

   

accounts/templates/accounts/navbar.html
<!-- html from bootstrap for navigation bar -->
{% load static %}
{% load group_tags %}


<style>
  .name-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="{% static '/media/logo.png' %}" width="100" height="40" alt="ISEI Logo">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

        {% if request.user|in_group:"admin"%}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin_dashboard' %}">Home </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_dashboard' %}">Teachers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin_dashboard' %}">Activities</a>
              </li>
        {% endif %}

        {% if request.user|in_group:"principal"%}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'principal_dashboard' %}">Home </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'teacher_certification' %}">Teacher Certification</a>
              </li>
              <li class="nav-item dropdown">
                  <div class="dropdown">
                        <button class="dropbtn">Documents and Resources
                          <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                          <a href="#">ISEI Codebook</a>
                          <a href="#">Teacher Certification Codebook</a>
                          <a href="#">Evaluation Forms</a>
                        </div>
                  </div>
                <!-- <a class="nav-link" href="{% url 'principal_dashboard' %}">Documents and Resources</a> -->
            </li>
              <li class="nav-item">
                    <a class="nav-link" href="{% url 'teacher_dashboard' %}">My Dashboard </a>
              </li>

              <li class="nav-item">
                    <a class="nav-link" href="{% url 'myPDAdashboard' request.user.id %}">My PD Activities</a>
              </li>

            <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_settings' %}">Settings</a>
              </li>
          {% else %}

              {% if request.user|in_group:"teacher"%}
                   <li class="nav-item active">
                    <a class="nav-link" href="{% url 'teacher_dashboard' %}">Home </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'myPDAdashboard' request.user.id %}">PD Activities</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_settings' %}">Settings</a>
                  </li>
              {% endif %}
        {% endif %}
        </ul>
  </div>


  <span class ="name-msg"> {{request.user.first_name}} </span>
  <span class ="name-msg"> <a href="{% url 'logout' %}">Logout</a> </span>
</nav>

accounts/templates/accounts/password_reset.html
<!DOCTYPE html>
<html>
 {% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>

<h3> Password reset </h3>

<p> Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one. </p>

<form method = "POST">
	{% csrf_token %}
	{{form}}
	<input type= "submit" value = "Send Email">
</form>
</body>

accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
<html>
 {% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>

	<h3>Password reset complete</h3>
	          

	<p>Your password has been set.  You may go ahead and log in now.</p>

	<p><a href="/">Log in</a></p>


	          
	          <br class="clear">
	        </div>
</body>
</html>

accounts/templates/accounts/password_reset_sent.html
<!DOCTYPE html>
<html>
 {% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<body>

	<h3> Password reset sent </h3>

	<p> We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

	<p> If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
	</p>

	</body>
</html>

accounts/templates/accounts/status.html
<br>

<div class="row">
	

	<div class="col">
		<div class="col-md-3">
			<div class="card text-center text-black  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h8 class="card-title">Total Teachers</h8>
			  	</div>
			  	<div class="card-body">
			    	<h8 class="card-title">{{total_teachers}}</h8>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md-5">
			<div class="card text-center text-black  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h8 class="card-title">Total Activities</h8>
			  	</div>
			  	<div class="card-body">
			    	<h8 class="card-title">{{total_activities}}</h8>
			  	</div>
			</div>
		</div>
	</div>
</div>

accounts/templates/accounts/supporting_document_upload.html
{% extends 'accounts/main.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'teacher_dashboard' %}">Return to home</a></p>
{% endblock %}

accounts/templates/accounts/teachers.html
{% extends 'accounts/main.html' %} 

{% block content %}	

<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">
				{{my_filter.form}}
		    	<button class="btn btn-primary" type="submit">Search</button>
		  	</form>
		</div>
	</div>
</div>

<div class="row">
	<div class="col">
		<h5>TEACHERS:</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-default  btn-sm btn-block"  href=""> Add Teacher </a>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Teacher</th>
					<th>Current Certification</th>
					<th>School</th>
				</tr>
				{% for teacher in teachers %}
					<tr>
						<td><a class = "btn btn-sm btn-info" href="{% url 'teacher' teacher.user.id %}">View</a></td>
						<td>{{teacher}} </td>
						<td>{{teacher.get_current_certification_display }} </td>
						<td>{{teacher.school}} </td>
					</tr>	

				{% endfor %}
					

			</table>
		</div>
	</div>

<div class="row">
		<div class="col-md-3">
			<div class="card text-center text-black  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5> class="card-title">Total Teachers</h5>
			  	</div>
			  	<div class="card-body">
			    	<h5> class="card-title">{{total_teachers}}</h5>
			  	</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}